# Generated by Django 3.1.5 on 2023-07-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_japanese_korean_delete_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='fastfood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='menu/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='yangsig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='menu/%Y/%m/%d')),
            ],
        ),
    ]
